### ISSUE TITLE
Crashing / Will not connect in 3.0 beta 5827 (v. 2.0.1)

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-globalcache-itac-cc#6]
The module will not connect and crashes in the latest betas, including with v 2.0.1.  I have tried a new instance and a restart of Companion with no effect.

**Comment by obcocav** [comment]
Meant to add that the last build I had without issues was 5824.

**Comment by obcocav** [comment]
Just tried 2.0.3 on 5830 and still same issue.  Won’t connect or bring up config screen and crashes.

**Comment by josephdadams** [comment]
fixed
