### ISSUE TITLE
Crashes in Companion Version 3.0.0

### ISSUE THREAD

**Issue by isaacclausen** [bitfocus/companion-module-globalcache-itac-cc#7]
I updated companion to version 3 and now the module never connects. I get "Crashed" in the status column after it tries to connect and "Connection config unavailable" in the Edit Connection column. I have Global Cache: iTach IP2CC v2.0.4 and Companion v3.0.0-rc2.

**Comment by josephdadams** [comment]
Any errors in the log or the >_ tab?

**Comment by isaacclausen** [comment]
No... nothing in the log from this module, and  >_  just has the buttons along the top with no entries

**Comment by josephdadams** [comment]
Try stopping and then starting the connection from that terminal page.

**Comment by isaacclausen** [comment]
Ok, looks like these two errors repeated:
`error: /private/var/folders/w_/c3b769b57pvdw8hz4m96krp1j9hdcw/T/AppTranslocation/410D3580-ADAB-41AE-AA9E-3254AE87C6E3/d/Companion.app/Contents/Resources/bundled-modules/globalcache-itac-cc/main.js:2
(()=>{var e={6010:(e,t,n)=>{const{InstanceBase:s,InstanceStatus:r,Regex:i,runEntrypoint:o,TCPHelper:a}=n(8049),c=n(4556),u=n(9182),l=n(5144),d=n(7417),p=n(4049),h=n(3125),f=n(3555);o(class extends s{constructor(e){super(e),Object.assign(this,{...u,...l,...d,...p,...h,...f}),this.socket=void 0,this.CHOICES_PORTS=[{id:"1",label:"Port 1"},{id:"2",label:"Port 2"},{id:"3",label:"Port 3"},{id:"4",label:"Port 4"},{id:"5",label:"Port 5"},{id:"6",label:"Port 6"}],this.DATA=[{port:"1",state:"0"},{port:"2",state:"0"},{port:"3",state:"0"},{port:"4",state:"0"},{port:"5",state:"0"},{port:"6",state:"0"}]}async destroy(){void 0!==this.socket&&this.socket.destroy(),void 0!==this.pollTimer&&(clearInterval(this.pollTimer),delete this.pollTimer)}async init(e){this.updateStatus(r.Connecting),this.configUpdated(e)}async configUpdated(e){void 0!==this.pollTimer&&(clearInterval(this.pollTimer),delete this.pollTimer),this.config=e,this.CHOICES_PORTS=[];for(let e=1;e<=this.config.ports;e++)this.CHOICES_PORTS.push({id:e.toString(),label:`Port ${e.toString()}`});this.initActions(),this.initFeedbacks(),this.initVariables(),this.initPresets(),this.initTCP()}initTCP(){let e=this;void 0!==e.socket&&(e.socket.destroy(),delete e.socket),e.config.host&&(e.socket=new a(this.config.host,4998),e.socket.on("connect",(()=>{e.updateStatus(r.Ok),e.log("debug","Connected"),e.startPolling()})),e.socket.on("data",(t=>{e.log("debug","Received: "+t);let n=t.toString().split("\r\n");for(let t=0;t<n.length;t++){let s=n[t].match(/state,(\d+):(\d+),(\d+)/);if(s){let t=s[2],n=s[3];e.updatePortState(t,n)}}})),e.socket.on("error",(function(t){e.log("error","Network error: "+t.message),clearInterval(e.pollTimer)})))}startPolling(){let e=this;e.config.poll_interval>0&&(e.pollTimer=setInterval((()=>{e.getStates()}),e.config.poll_interval))}getStates(){let e=this;for(let t=1;t<=e.config.ports;t++){let n=`getstate,1:${t}`;e.sendCommand(n)}}updatePortState(e,t){let n=this;for(let s=0;s<n.DATA.length;s++)if(n.DATA[s],n.DATA[s].port==e){n.DATA[s].state=t,n.checkFeedbacks("relaystate"),n.checkVariables();break}}sendCommand(e){let t=this;void 0!==e&&(void 0!==t.socket&&t.socket.isConnected?(t.log("debug","Sending: "+e),t.socket.send(e+"\r\n").then((e=>{})).catch((e=>{}))):(t.log("error","Network error: Connection to Device not opened."),clearInterval(t.pollTimer)))}},c)},7056:(e,t,n)=>{"use strict";const s=n(4063);s.code='require("ajv/dist/runtime/equal").default',t.Z=s},1460:(e,t,n)=>{"use strict";n.r(t),n.d(t,{__assign:()=>i,__asyncDelegator:()=>w,__asyncGenerator:()=>T,__asyncValues:()=>x,__await:()=>k,__awaiter:()=>f,__classPrivateFieldGet:()=>N,__classPrivateFieldIn:()=>D,__classPrivateFieldSet:()=>A,__createBinding:()=>g,__decorate:()=>a,__esDecorate:()=>u,__exportStar:()=>m,__extends:()=>r,__generator:()=>_,__importDefault:()=>R,__importStar:()=>O,__makeTemplateObject:()=>I,__metadata:()=>h,__param:()=>c,__propKey:()=>d,__read:()=>b,__rest:()=>o,__runInitializers:()=>l,__setFunctionName:()=>p,__spread:()=>v,__spreadArray:()=>E,__spreadArrays:()=>S,__values:()=>y});var s=function(e,t){return s=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(e[n]=t[n])},s(e,t)};function r(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Class extends value "+String(t)+" is not a constructor or null");function n(){this.constructor=e}s(e,t),e.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}var i=function(){return i=Object.assign||function(e){for(var t,n=1,s=arguments.length;n<s;n++)for(var r in t=arguments[n])Object.prototype.hasOwnProperty.call(t,r)&&(e[r]=t[r]);return e},i.apply(this,arguments)};function o(e,t){var n={};for(var s in e)Object.prototype.hasOwnProperty.call(e,s)&&t.indexOf(s)<0&&(n[s]=e[s]);if(null!=e&&"function"==typeof Object.getOwnPropertySymbols){var r=0;for(s=Object.getOwnPropertySymbols(e);r<s.length;r++)t.indexOf(s[r])<0&&Object.prototype.propertyIsEnumerable.call(e,s[r])&&(n[s[r]]=e[s[r]])}return n}function a(e,t,n,s){var r,i=arguments.length,o=i<3?t:null===s?s=Object.getOwnPropertyDescriptor(t,n):s;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)o=Reflect.decorate(e,t,n,s);else for(var a=e.length-1;a>=0;a--)(r=e[a])&&(o=(i<3?r(o):i>3?r(t,n,o):r(t,n))||o);return i>3&&o&&Object.defineProperty(t,n,o),o}function c(e,t){return function(n,s){t(n,s,e)}}function u(e,t,n,s,r,i){function o(e){if(void 0!==e&&"function"!=typeof e)throw new TypeError("Function expected");return e}for(var a,c=s.kind,u="getter"===c?"get":"setter"===c?"set":"value",l=!t&&e?s.static?e:e.prototype:null,d=t||(l?Object.getOwnPropertyDescriptor(l,s.name):{}),p=!1,h=n.length-1;h>=0;h--){var f={};for(var _ in s)f[_]="access"===_?{}:s[_];for(var _ in s.access)f.access[_]=s.access[_];f.addInitializer=function(e){if(p)throw new TypeError("Cannot add initializers after decoration has completed");i.push(o(e||null))};var g=(0,n[h])("accessor"===c?{get:d.get,set:d.set}:d[u],f);if("accessor"===c){if(void 0===g)continue;if(null===g||"object"!=typeof g)throw new TypeError("Object expected");(a=o(g.get))&&(d.get=a),(a=o(g.set))&&(d.set=a),(a=o(g.init))&&r.push(a)}else(a=o(g))&&("field"===c?r.push(a):d[u]=a)}l&&Object.defineProperty(l,s.name,d),p=!0}function l(e,t,n){for(var s=arguments.length>2,r=0;r<t.length;r++)n=s?t[r].call(e,n):t[r].call(e);return s?n:void 0}function d(e){return"symbol"==typeof e?e:"".concat(e)}function p(e,t,n){return"symbol"==typeof t&&(t=t.description?"[".concat(t.description,"]"):""),Object.defineProperty(e,"name",{configurable:!0,value:n?"".concat(n," ",t):t})}function h(e,t){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(e,t)}function f(e,t,n,s){return new(n||(n=Promise))((function(r,i){function o(e){try{c(s.next(e))}catch(e){i(e)}}function a(e){try{c(s.throw(e))}catch(e){i(e)}}function c(e){var t;e.done?r(e.value):(t=e.value,t instanceof n?t:new n((function(e){e(t)}))).then(o,a)}c((s=s.apply(e,t||[])).next())}))}function _(e,t){var n,s,r,i,o={label:0,sent:function(){if(1&r[0])throw r[1];return r[1]},trys:[],ops:[]};return i={next:a(0),throw:a(1),return:a(2)},"function"==typeof Symbol&&(i[Symbol.iterator]=function(){return this}),i;function a(a){return function(c){return function(a){if(n)throw new TypeError("Generator is already executing.");for(;i&&(i=0,a[0]&&(o=0)),o;)try{if(n=1,s&&(r=2&a[0]?s.return:a[0]?s.throw||((r=s.return)&&r.call(s),0):s.next)&&!(r=r.call(s,a[1])).done)return r;switch(s=0,r&&(a=[2&a[0],r.value]),a[0]){case 0:case 1:r=a;break;case 4:return o.label++,{value:a[1],done:!1};case 5:o.label++,s=a[1],a=[0];continue;case 7:a=o.ops.pop(),o.trys.pop();continue;default:if(!((r=(r=o.trys).length>0&&r[r.length-1])||6!==a[0]&&2!==a[0])){o=0;continue}if(3===a[0]&&(!r||a[1]>r[0]&&a[1]<r[3])){o.label=a[1];break}if(6===a[0]&&o.label<r[1]){o.label=r[1],r=a;break}if(r&&o.label<r[2]){o.label=r[2],o.ops.push(a);break}r[2]&&o.ops.pop(),o.trys.pop();continue}a=t.call(e,o)}catch(e){a=[6,e],s=0}finally{n=r=0}if(5&a[0])throw a[1];return{value:a[0]?a[1]:void 0,done:!0}}([a,c])}}}var g=Object.create?function(e,t,n,s){void 0===s&&(s=n);var r=Object.getOwnPropertyDescriptor(t,n);r&&!("get"in r?!t.__esModule:r.writable||r.configurable)||(r={enumerable:!0,get:function(){return t[n]}}),Object.defineProperty(e,s,r)}:function(e,t,n,s){void 0===s&&(s=n),e[s]=t[n]};function m(e,t){for(var n in e)"default"===n||Object.prototype.hasOwnProperty.call(t,n)||g(t,e,n)}function y(e){var t="function"==typeof Symbol&&Symbol.iterator,n=t&&e[t],s=0;if(n)return n.call(e);if(e&&"number"==typeof e.length)return{next:function(){return e&&s>=e.length&&(e=void 0),{value:e&&e[s++],done:!e}}};throw new TypeError(t?"Object is not iterable.":"Symbol.iterator is not defined.")}function b(e,t){var n="function"==typeof Symbol&&e[Symbol.iterator];if(!n)return e;var s,r,i=n.call(e),o=[];try{for(;(void 0===t||t-- >0)&&!(s=i.next()).done;)o.push(s.value)}catch(e){r={err

error: Failed to init: Error: Call timed out Error: Call timed out
    at t.IpcWrapper.sendWithCb (/private/var/folders/w_/c3b769b57pvdw8hz4m96krp1j9hdcw/T/AppTranslocation/410D3580-ADAB-41AE-AA9E-3254AE87C6E3/d/Companion.app/Contents/Resources/main.js:2:2362159)
    at Object.init (/private/var/folders/w_/c3b769b57pvdw8hz4m96krp1j9hdcw/T/AppTranslocation/410D3580-ADAB-41AE-AA9E-3254AE87C6E3/d/Companion.app/Contents/Resources/main.js:2:8087748)
    at l.<anonymous> (/private/var/folders/w_/c3b769b57pvdw8hz4m96krp1j9hdcw/T/AppTranslocation/410D3580-ADAB-41AE-AA9E-3254AE87C6E3/d/Companion.app/Contents/Resources/main.js:2:8096617)
    at l.emit (node:events:513:28)
    at l.emit (node:domain:489:12)
    at ChildProcess.<anonymous> (/private/var/folders/w_/c3b769b57pvdw8hz4m96krp1j9hdcw/T/AppTranslocation/410D3580-ADAB-41AE-AA9E-3254AE87C6E3/d/Companion.app/Contents/Resources/main.js:2:2349720)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)`

**Comment by isaacclausen** [comment]
Looks like it crashes with the same errors in 3.0.1.

**Comment by isaacclausen** [comment]
Is this an issue with my system? is there something else I should try?  I've tried it now in 3.1.0 and have these errors in the log still:
[module-log-10_6_2023-11_36_12 AM.csv](https://github.com/bitfocus/companion-module-globalcache-itac-cc/files/12833387/module-log-10_6_2023-11_36_12.AM.csv)

**Comment by josephdadams** [comment]
I just pushed v2.0.5 of the module, if you want to try out a beta, make sure it is this version of the module. Let me know if it makes any difference for you.

**Comment by isaacclausen** [comment]
Ah... I seemed to have fixed it. In 3.1, I added another instance of the module and that one didn't crash. Interesting. Thank you for our help.
